class SeeingIsBelieving
  # all our errors will inherit from this so that a user
  # can catch any error generated by this lib
  SeeingIsBelievingError = Class.new StandardError

  class TempFileAlreadyExists < SeeingIsBelievingError
    def initialize(from_filename, temp_filename)
      super "Trying to back up #{from_filename.inspect} (FILE) to"\
            " #{temp_filename.inspect} (TEMPFILE) but TEMPFILE already exists."\
            " You should check the contents of these files. If FILE is correct,"\
            " then delete TEMPFILE. Otherwise rename TEMPFILE to FILE."
    end
  end

  class BugInSib < SeeingIsBelievingError
    def initialize(error)
      require 'parser/version'
      require 'seeing_is_believing/version'

      super "It blew up >.< Please log an issue at: https://github.com/JoshCheek/seeing_is_believing/issues\n"\
            "SeeingIsBelieving::VERSION  #{SeeingIsBelieving::VERSION.inspect}\n"\
            "Parser::VERSION             #{Parser::VERSION.inspect}\n"\
            "RUBY_VERSION                #{RUBY_VERSION.inspect}\n"\
            "ENV['RUBY_VERSION']         #{ENV['RUBY_VERSION'].inspect}\n"\
            "Also include the source code of program that caused this behaviour."
    end
  end
end
