class SeeingIsBelieving
  # all our errors will inherit from this so that a user
  # can catch any error generated by this lib
  SeeingIsBelievingError = Class.new StandardError

  TempFileAlreadyExists = Class.new SeeingIsBelievingError
end
